package GUI;

import Logik.*;
import java.awt.Font;
import static java.awt.Font.PLAIN;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mouid
 */
public class PickColorFrame extends javax.swing.JFrame {

    private Card.KarteFarbe farbe = null;
    boolean A = false;
    PopUp popUp;
    /**
     * Creates new form PickColorFrame
     */
    public PickColorFrame() {
        initComponents();
    }
    
    public PickColorFrame(PopUp ppup) {
        initComponents();
        popUp = ppup;
    }
    
    public Card.KarteFarbe farbeWaehlen(Card karte){
        if (karte.getColor()== Card.KarteFarbe.BESONDERE){
            this.setVisible(true);
            this.setResizable(false);
            this.setBounds(200,200,600,600);
        }
        return karte.getColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jGelbButton = new javax.swing.JButton();
        jBlauButton = new javax.swing.JButton();
        jRotButton = new javax.swing.JButton();
        jGruenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Waehlen Sie eine Farbe");

        jGelbButton.setBackground(new java.awt.Color(102, 102, 102));
        jGelbButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jGelbButton.setForeground(new java.awt.Color(153, 153, 0));
        jGelbButton.setText("GELB");
        jGelbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGelbButtonActionPerformed(evt);
            }
        });

        jBlauButton.setBackground(new java.awt.Color(102, 102, 102));
        jBlauButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBlauButton.setForeground(new java.awt.Color(0, 51, 255));
        jBlauButton.setText("BLAU");
        jBlauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlauButtonActionPerformed(evt);
            }
        });

        jRotButton.setBackground(new java.awt.Color(102, 102, 102));
        jRotButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jRotButton.setForeground(new java.awt.Color(204, 0, 0));
        jRotButton.setText("ROT");
        jRotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRotButtonActionPerformed(evt);
            }
        });

        jGruenButton.setBackground(new java.awt.Color(102, 102, 102));
        jGruenButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jGruenButton.setForeground(new java.awt.Color(0, 255, 51));
        jGruenButton.setText("GRUEN");
        jGruenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGruenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBlauButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGruenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jGelbButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jRotButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBlauButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGruenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGelbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBlauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlauButtonActionPerformed
        // TODO add your handling code here:
        farbe = Card.KarteFarbe.BLAU;
        JLabel l = new JLabel("Die besondere Karte hat dann die Farbe Blau");
        l.setFont(new Font("Segoe UI Black",PLAIN,18));
        JOptionPane.showMessageDialog(null,l);
        A = true;
        this.dispose();
        popUp.gewaehlteFarbe=Card.KarteFarbe.BLAU;
        //popUp.gameStage.setSpielerId();
        popUp.gameStage.setButtonIcons();
        popUp.obereKarteButton.setIcon(new javax.swing.ImageIcon("Einos-Bilder/PNGs/small/"+popUp.game.getTopCardImage()));
        //popUp.game.setKarteFarbe(Card.KarteFarbe.BLAU);
        popUp.dispose();
    }//GEN-LAST:event_jBlauButtonActionPerformed

    private void jRotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRotButtonActionPerformed
        // TODO add your handling code here:
        farbe = Card.KarteFarbe.ROT;
        JLabel l = new JLabel("Die besondere Karte hat dann die Farbe Rot!");
        l.setFont(new Font("Segoe UI Black",PLAIN,18));
        JOptionPane.showMessageDialog(null,l);
        A = true;
        this.dispose();
        popUp.gewaehlteFarbe=Card.KarteFarbe.ROT;
        //popUp.gameStage.setSpielerId();
        popUp.gameStage.setButtonIcons();
        popUp.obereKarteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Einos-Bilder/PNGs/large/"+popUp.game.getTopCardImage())));
        //popUp.game.setKarteFarbe(Card.KarteFarbe.ROT);
        popUp.dispose();
        
    }//GEN-LAST:event_jRotButtonActionPerformed

    private void jGruenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGruenButtonActionPerformed
        // TODO add your handling code here:
        farbe = Card.KarteFarbe.GRUEN;
        JLabel l = new JLabel("Die besondere Karte hat dann die Farbe Gruen!");
        l.setFont(new Font("Segoe UI Black",PLAIN,18));
        JOptionPane.showMessageDialog(null,l);
        A = true;
        this.dispose();
        popUp.gewaehlteFarbe=Card.KarteFarbe.GRUEN;
        //popUp.gameStage.setSpielerId();
        popUp.gameStage.setButtonIcons();
        popUp.obereKarteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Einos-Bilder/PNGs/large/"+popUp.game.getTopCardImage())));
        //popUp.game.setKarteFarbe(Card.KarteFarbe.GRUEN);
        popUp.dispose();
    }//GEN-LAST:event_jGruenButtonActionPerformed

    private void jGelbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGelbButtonActionPerformed
        // TODO add your handling code here:
        farbe = Card.KarteFarbe.GELB;
        JLabel l = new JLabel("Die besondere Karte hat dann die Farbe gelb!");
        l.setFont(new Font("Segoe UI Black",PLAIN,18));
        JOptionPane.showMessageDialog(null,l);
        A = true;
        this.dispose();
        popUp.gewaehlteFarbe=Card.KarteFarbe.GELB;
        //popUp.gameStage.setSpielerId();
        popUp.gameStage.setButtonIcons();
        popUp.obereKarteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Einos-Bilder/PNGs/small/"+popUp.game.getTopCardImage())));
        //popUp.game.setKarteFarbe(Card.KarteFarbe.GELB);
        popUp.dispose();
    }//GEN-LAST:event_jGelbButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickColorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBlauButton;
    private javax.swing.JButton jGelbButton;
    private javax.swing.JButton jGruenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jRotButton;
    // End of variables declaration//GEN-END:variables
}
