package GUI;

import Logik.*;
import Logik.Game.UngultigSpielerZugException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mouid
 */
public class PopUp extends javax.swing.JFrame {
    
    String KarteImage = "";
    Game game;
    ArrayList<Card> spielerHand ;
    int choice;
    ArrayList<JButton> buttonsVonKarten;
    GameStage gameStage;
    JButton obereKarteButton;
    Card.KarteFarbe gewaehlteFarbe;
    public PopUp(){
        
    }

    /**
     * Creates new form PopUp
     */
    public PopUp(String KarteImage ,Game game, int index ,ArrayList<JButton> buttonsVonKarten,GameStage gameStage,JButton obereKarteButton){
        initComponents();
        this.KarteImage = KarteImage;
        this.game = game;
        if ( game.Zug % 2 !=0){this.spielerHand=game.getSpielerHand(game.SpielerID[0]);}
        else if ( game.Zug % 2 == 0){this.spielerHand=game.getSpielerHand(game.SpielerID[1]);}
        choice = index;
        this.buttonsVonKarten= buttonsVonKarten;
        CardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("Einos-Bilder/PNGs/large/"+ KarteImage+".png")));
        this.gameStage = gameStage;
        this.obereKarteButton=obereKarteButton;
        gewaehlteFarbe = Deck.toCard1(KarteImage).getColor();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UseCardButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        CardLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UseCardButton.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        UseCardButton.setText("Karte spielen ");
        UseCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseCardButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Mistral", 0, 24)); // NOI18N
        CancelButton.setText("Nein!");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(UseCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(CardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(CardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UseCardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void UseCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseCardButtonActionPerformed
        
        
        game.Zuege.add(game.Zug);
        int h = game.Zug;
        
        if (Deck.toCard1(KarteImage).getValue()== Card.Wert.UEBERSPRINGEN || Deck.toCard1(KarteImage).getValue()== Card.Wert.UMKEHREN  ){}
        else {game.Zug++;}
        
        if ( game.Zug % 2 != 0 && game.Zug != 0 && game.Zug>h){
            if ( gewaehlteFarbe != Card.KarteFarbe.BESONDERE){
               game.scannenUndEineKarteSpielenFuerErsteSpieler(KarteImage); gameStage.setButtonIcons();
            }else {
                game.scannenUndEineKarteSpielenFuerErsteSpieler(KarteImage,gewaehlteFarbe.toString()); gameStage.setButtonIcons();
            }
            
        }
        else if (game.Zug % 2 == 0){
            if ( gewaehlteFarbe != Card.KarteFarbe.BESONDERE){
               game.scannenUndEineKarteSpielenFuerZweiteSpieler(KarteImage); gameStage.setButtonIcons();
            }else {
                game.scannenUndEineKarteSpielenFuerZweiteSpieler(KarteImage,gewaehlteFarbe.toString()); gameStage.setButtonIcons();
            }
        } 
        
        
        //this.revalidate();
        /*if ( gewaehlteFarbe != Card.KarteFarbe.BESONDERE){
            //gameStage.setSpielerId();
            gameStage.setButtonIcons();
            obereKarteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("Einos-Bilder/PNGs/small/"+ KarteImage+".png")));
            this.dispose();
        }  */
        gameStage.setButtonIcons();
        this.dispose();
    }//GEN-LAST:event_UseCardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CardLabel;
    private javax.swing.JButton UseCardButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
